#!/usr/bin/env python3
"""Generate the Markdown handler reference from Python docstrings."""

from __future__ import annotations

import argparse
import inspect
import re
from pathlib import Path
from types import FunctionType
from typing import Any

from gppu import handlers

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "docs" / "handlers.md"
ROLE = re.compile(r":(?:class|func|meth|mod):`([^`]+)`")
PUBLIC_MAGIC = {"__call__"}


def _markdown(text: str | None) -> str:
    """Convert the small reStructuredText subset in docstrings to Markdown."""

    if text is None:
        return ""
    value = inspect.cleandoc(text)
    value = ROLE.sub(r"`\1`", value)
    value = re.sub(r"``([^`]+)``", r"`\1`", value)
    return value.replace("::\n", ":\n")


def _signature(value: Any) -> str:
    """Return an inspectable signature or an empty string."""

    try:
        return str(inspect.signature(value))
    except TypeError, ValueError:
        return ""


def _member(value: Any) -> tuple[Any, str] | None:
    """Return a documented class member and its display kind."""

    if isinstance(value, property):
        return value.fget, "property"
    if isinstance(value, (classmethod, staticmethod)):
        return value.__func__, "method"
    if isinstance(value, FunctionType):
        return value, "method"
    return None


def _classes() -> tuple[type[Any], ...]:
    """Return public classes declared by ``gppu.handlers`` in source order."""

    found = (
        value
        for name, value in vars(handlers).items()
        if not name.startswith("_")
        and inspect.isclass(value)
        and value.__module__ == handlers.__name__
    )
    return tuple(sorted(found, key=lambda value: inspect.getsourcelines(value)[1]))


def _functions() -> tuple[FunctionType, ...]:
    """Return public functions declared by ``gppu.handlers`` in source order."""

    found = (
        value
        for name, value in vars(handlers).items()
        if not name.startswith("_")
        and inspect.isfunction(value)
        and value.__module__ == handlers.__name__
    )
    return tuple(sorted(found, key=lambda value: inspect.getsourcelines(value)[1]))


def render() -> str:
    """Render the complete generated handler reference."""

    lines = [
        "<!-- Generated by scripts/generate_handlers_docs.py from gppu/handlers.py. -->",
        "# gppu.handlers",
        "",
        _markdown(handlers.__doc__),
    ]
    for cls in _classes():
        lines.extend(
            [
                "",
                f"## `{cls.__name__}{_signature(cls)}`",
                "",
                _markdown(cls.__doc__),
            ]
        )
        for name, value in cls.__dict__.items():
            if name.startswith("_") and name not in PUBLIC_MAGIC:
                continue
            member = _member(value)
            if member is None:
                continue
            item, kind = member
            if not item.__doc__:
                continue
            suffix = "" if kind == "property" else _signature(item)
            lines.extend(
                [
                    "",
                    f"### `{cls.__name__}.{name}{suffix}`",
                    "",
                    _markdown(item.__doc__),
                ]
            )
    for function in _functions():
        lines.extend(
            [
                "",
                f"## `{function.__name__}{_signature(function)}`",
                "",
                _markdown(function.__doc__),
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    """Write the reference, or verify that its committed copy is current."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    rendered = render()
    if arguments.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"{OUTPUT}: regenerate with {Path(__file__).name}")
        return
    OUTPUT.write_text(rendered, encoding="utf-8")


if __name__ == "__main__":
    main()
